# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forth.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        #Form.resize(997, 564)
        Form.setFixedSize(1000, 650)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.MovieInfoLeft = QtWidgets.QFrame(Form)
        self.MovieInfoLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MovieInfoLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MovieInfoLeft.setObjectName("MovieInfoLeft")
        self.gridLayout = QtWidgets.QGridLayout(self.MovieInfoLeft)
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(self.MovieInfoLeft)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.toolButton81 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton81.setObjectName("toolButton81")
        self.horizontalLayout_29.addWidget(self.toolButton81)
        self.ButtonName8 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.ButtonName8.setObjectName("ButtonName8")
        self.horizontalLayout_29.addWidget(self.ButtonName8)
        self.toolButton82 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton82.setObjectName("toolButton82")
        self.horizontalLayout_29.addWidget(self.toolButton82)
        self.gridLayout.addLayout(self.horizontalLayout_29, 5, 1, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.toolButton61 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton61.setObjectName("toolButton61")
        self.horizontalLayout_27.addWidget(self.toolButton61)
        self.ButtonName6 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.ButtonName6.setObjectName("ButtonName6")
        self.horizontalLayout_27.addWidget(self.ButtonName6)
        self.toolButton62 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton62.setObjectName("toolButton62")
        self.horizontalLayout_27.addWidget(self.toolButton62)
        self.gridLayout.addLayout(self.horizontalLayout_27, 3, 2, 1, 1)
        self.label5 = QtWidgets.QLabel(self.MovieInfoLeft)
        self.label5.setObjectName("label5")
        self.gridLayout.addWidget(self.label5, 2, 1, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.toolButton51 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton51.setObjectName("toolButton51")
        self.horizontalLayout_26.addWidget(self.toolButton51)
        self.ButtonName5 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.ButtonName5.setObjectName("ButtonName5")
        self.horizontalLayout_26.addWidget(self.ButtonName5)
        self.toolButton52 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton52.setObjectName("toolButton52")
        self.horizontalLayout_26.addWidget(self.toolButton52)
        self.gridLayout.addLayout(self.horizontalLayout_26, 3, 1, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.toolButton41 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton41.setObjectName("toolButton41")
        self.horizontalLayout_23.addWidget(self.toolButton41)
        self.ButtonName4 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.ButtonName4.setObjectName("ButtonName4")
        self.horizontalLayout_23.addWidget(self.ButtonName4)
        self.toolButton42 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton42.setObjectName("toolButton42")
        self.horizontalLayout_23.addWidget(self.toolButton42)
        self.gridLayout.addLayout(self.horizontalLayout_23, 3, 0, 1, 1)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.toolButton91 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton91.setObjectName("toolButton91")
        self.horizontalLayout_30.addWidget(self.toolButton91)
        self.ButtonName9 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.ButtonName9.setObjectName("ButtonName9")
        self.horizontalLayout_30.addWidget(self.ButtonName9)
        self.toolButton92 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton92.setObjectName("toolButton92")
        self.horizontalLayout_30.addWidget(self.toolButton92)
        self.gridLayout.addLayout(self.horizontalLayout_30, 5, 2, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.toolButton21 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton21.setObjectName("toolButton21")
        self.horizontalLayout_24.addWidget(self.toolButton21)
        self.ButtonName2 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.ButtonName2.setObjectName("ButtonName2")
        self.horizontalLayout_24.addWidget(self.ButtonName2)
        self.toolButton22 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton22.setObjectName("toolButton22")
        self.horizontalLayout_24.addWidget(self.toolButton22)
        self.gridLayout.addLayout(self.horizontalLayout_24, 1, 1, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.toolButton31 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton31.setObjectName("toolButton31")
        self.horizontalLayout_25.addWidget(self.toolButton31)
        self.ButtonName3 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.ButtonName3.setObjectName("ButtonName3")
        self.horizontalLayout_25.addWidget(self.ButtonName3)
        self.toolButton32 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton32.setObjectName("toolButton32")
        self.horizontalLayout_25.addWidget(self.toolButton32)
        self.gridLayout.addLayout(self.horizontalLayout_25, 1, 2, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.toolButton11 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton11.setObjectName("toolButton11")
        self.horizontalLayout_11.addWidget(self.toolButton11)
        self.ButtonName1 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.ButtonName1.setObjectName("ButtonName1")
        self.horizontalLayout_11.addWidget(self.ButtonName1)
        self.toolButton12 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton12.setObjectName("toolButton12")
        self.horizontalLayout_11.addWidget(self.toolButton12)
        self.gridLayout.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(self.MovieInfoLeft)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 0, 1, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.toolButton71 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton71.setObjectName("toolButton71")
        self.horizontalLayout_28.addWidget(self.toolButton71)
        self.ButtonName7 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.ButtonName7.setObjectName("ButtonName7")
        self.horizontalLayout_28.addWidget(self.ButtonName7)
        self.toolButton72 = QtWidgets.QToolButton(self.MovieInfoLeft)
        self.toolButton72.setObjectName("toolButton72")
        self.horizontalLayout_28.addWidget(self.toolButton72)
        self.gridLayout.addLayout(self.horizontalLayout_28, 5, 0, 1, 1)
        self.label3 = QtWidgets.QLabel(self.MovieInfoLeft)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 0, 2, 1, 1)
        self.label4 = QtWidgets.QLabel(self.MovieInfoLeft)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 2, 0, 1, 1)
        self.label6 = QtWidgets.QLabel(self.MovieInfoLeft)
        self.label6.setObjectName("label6")
        self.gridLayout.addWidget(self.label6, 2, 2, 1, 1)
        self.label9 = QtWidgets.QLabel(self.MovieInfoLeft)
        self.label9.setObjectName("label9")
        self.gridLayout.addWidget(self.label9, 4, 2, 1, 1)
        self.label8 = QtWidgets.QLabel(self.MovieInfoLeft)
        self.label8.setObjectName("label8")
        self.gridLayout.addWidget(self.label8, 4, 1, 1, 1)
        self.label7 = QtWidgets.QLabel(self.MovieInfoLeft)
        self.label7.setObjectName("label7")
        self.gridLayout.addWidget(self.label7, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.MovieInfoLeft)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.MovieInfoRight = QtWidgets.QFrame(Form)
        self.MovieInfoRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MovieInfoRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MovieInfoRight.setObjectName("MovieInfoRight")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MovieInfoRight)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PictureFrame = QtWidgets.QFrame(self.MovieInfoRight)
        self.PictureFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PictureFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PictureFrame.setObjectName("PictureFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.PictureFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Picture = QtWidgets.QLabel(self.PictureFrame)
        self.Picture.setObjectName("Picture")
        self.verticalLayout_3.addWidget(self.Picture)
        self.verticalLayout_2.addWidget(self.PictureFrame)
        self.IntroduceFrame = QtWidgets.QFrame(self.MovieInfoRight)
        self.IntroduceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.IntroduceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.IntroduceFrame.setObjectName("IntroduceFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.IntroduceFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Introduce = QtWidgets.QLabel(self.IntroduceFrame)
        self.Introduce.setObjectName("Introduce")
        self.verticalLayout_4.addWidget(self.Introduce)
        self.verticalLayout_2.addWidget(self.IntroduceFrame)
        self.CalFrame = QtWidgets.QFrame(self.MovieInfoRight)
        self.CalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CalFrame.setObjectName("CalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.CalFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.CalFrame)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_2.addWidget(self.calendarWidget)
        self.verticalLayout_2.addWidget(self.CalFrame)
        self.hallChoiceFrame = QtWidgets.QFrame(self.MovieInfoRight)
        self.hallChoiceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hallChoiceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hallChoiceFrame.setObjectName("hallChoiceFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.hallChoiceFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hall4 = QtWidgets.QPushButton(self.hallChoiceFrame)
        self.hall4.setObjectName("hall4")
        self.gridLayout_4.addWidget(self.hall4, 2, 0, 1, 1)
        self.hall8 = QtWidgets.QPushButton(self.hallChoiceFrame)
        self.hall8.setObjectName("hall8")
        self.gridLayout_4.addWidget(self.hall8, 3, 1, 1, 1)
        self.hall6 = QtWidgets.QPushButton(self.hallChoiceFrame)
        self.hall6.setObjectName("hall6")
        self.gridLayout_4.addWidget(self.hall6, 2, 2, 1, 1)
        self.hall2 = QtWidgets.QPushButton(self.hallChoiceFrame)
        self.hall2.setObjectName("hall2")
        self.gridLayout_4.addWidget(self.hall2, 1, 1, 1, 1)
        self.hall9 = QtWidgets.QPushButton(self.hallChoiceFrame)
        self.hall9.setObjectName("hall9")
        self.gridLayout_4.addWidget(self.hall9, 3, 2, 1, 1)
        self.hall5 = QtWidgets.QPushButton(self.hallChoiceFrame)
        self.hall5.setObjectName("hall5")
        self.gridLayout_4.addWidget(self.hall5, 2, 1, 1, 1)
        self.hall7 = QtWidgets.QPushButton(self.hallChoiceFrame)
        self.hall7.setObjectName("hall7")
        self.gridLayout_4.addWidget(self.hall7, 3, 0, 1, 1)
        self.hall1 = QtWidgets.QPushButton(self.hallChoiceFrame)
        self.hall1.setObjectName("hall1")
        self.gridLayout_4.addWidget(self.hall1, 1, 0, 1, 1)
        self.hall3 = QtWidgets.QPushButton(self.hallChoiceFrame)
        self.hall3.setObjectName("hall3")
        self.gridLayout_4.addWidget(self.hall3, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.hallChoiceFrame)
        self.horizontalLayout.addWidget(self.MovieInfoRight)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label1.setText(_translate("Form", "TextLabel"))
        self.toolButton81.setText(_translate("Form", "..."))
        self.ButtonName8.setText(_translate("Form", "..."))
        self.toolButton82.setText(_translate("Form", "..."))
        self.toolButton61.setText(_translate("Form", "..."))
        self.ButtonName6.setText(_translate("Form", "..."))
        self.toolButton62.setText(_translate("Form", "..."))
        self.label5.setText(_translate("Form", "TextLabel"))
        self.toolButton51.setText(_translate("Form", "..."))
        self.ButtonName5.setText(_translate("Form", "..."))
        self.toolButton52.setText(_translate("Form", "..."))
        self.toolButton41.setText(_translate("Form", "..."))
        self.ButtonName4.setText(_translate("Form", "..."))
        self.toolButton42.setText(_translate("Form", "..."))
        self.toolButton91.setText(_translate("Form", "..."))
        self.ButtonName9.setText(_translate("Form", "..."))
        self.toolButton92.setText(_translate("Form", "..."))
        self.toolButton21.setText(_translate("Form", "..."))
        self.ButtonName2.setText(_translate("Form", "DeadPool"))
        self.toolButton22.setText(_translate("Form", "..."))
        self.toolButton31.setText(_translate("Form", "..."))
        self.ButtonName3.setText(_translate("Form", "PikaPika"))
        self.toolButton32.setText(_translate("Form", "..."))
        self.toolButton11.setText(_translate("Form", "..."))
        self.ButtonName1.setText(_translate("Form", "pokemon"))
        self.toolButton12.setText(_translate("Form", "..."))
        self.label2.setText(_translate("Form", "TextLabel"))
        self.toolButton71.setText(_translate("Form", "..."))
        self.ButtonName7.setText(_translate("Form", "..."))
        self.toolButton72.setText(_translate("Form", "..."))
        self.label3.setText(_translate("Form", "TextLabel"))
        self.label4.setText(_translate("Form", "TextLabel"))
        self.label6.setText(_translate("Form", "TextLabel"))
        self.label9.setText(_translate("Form", "TextLabel"))
        self.label8.setText(_translate("Form", "TextLabel"))
        self.label7.setText(_translate("Form", "TextLabel"))
        self.Picture.setText(_translate("Form", "pic"))
        self.Introduce.setText(_translate("Form", "balabala...."))
        self.hall4.setText(_translate("Form", "Hall"))
        self.hall8.setText(_translate("Form", "Hall"))
        self.hall6.setText(_translate("Form", "Hall"))
        self.hall2.setText(_translate("Form", "Hall"))
        self.hall9.setText(_translate("Form", "Hall"))
        self.hall5.setText(_translate("Form", "Hall"))
        self.hall7.setText(_translate("Form", "Hall"))
        self.hall1.setText(_translate("Form", "Hall"))
        self.hall3.setText(_translate("Form", "Hall"))


