# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'man.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form4(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(653, 589)
        self.manwel = QtWidgets.QLabel(Form)
        self.manwel.setGeometry(QtCore.QRect(190, 0, 291, 121))
        self.manwel.setObjectName("manwel")
        self.newmvFrame = QtWidgets.QFrame(Form)
        self.newmvFrame.setGeometry(QtCore.QRect(250, 140, 361, 411))
        self.newmvFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newmvFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newmvFrame.setMidLineWidth(1)
        self.newmvFrame.setObjectName("newmvFrame")
        self.newMovie = QtWidgets.QLabel(self.newmvFrame)
        self.newMovie.setGeometry(QtCore.QRect(110, 30, 171, 31))
        self.newMovie.setObjectName("newMovie")
        self.mvname = QtWidgets.QLabel(self.newmvFrame)
        self.mvname.setGeometry(QtCore.QRect(20, 110, 67, 17))
        self.mvname.setObjectName("mvname")
        self.mvhall = QtWidgets.QLabel(self.newmvFrame)
        self.mvhall.setGeometry(QtCore.QRect(20, 160, 67, 17))
        self.mvhall.setObjectName("mvhall")
        self.mvprice = QtWidgets.QLabel(self.newmvFrame)
        self.mvprice.setGeometry(QtCore.QRect(20, 210, 67, 17))
        self.mvprice.setObjectName("mvprice")
        self.mvdate = QtWidgets.QLabel(self.newmvFrame)
        self.mvdate.setGeometry(QtCore.QRect(20, 250, 67, 17))
        self.mvdate.setObjectName("mvdate")
        self.mvnameLine = QtWidgets.QLineEdit(self.newmvFrame)
        self.mvnameLine.setGeometry(QtCore.QRect(110, 100, 161, 27))
        self.mvnameLine.setObjectName("mvnameLine")
        self.mvhallLine = QtWidgets.QLineEdit(self.newmvFrame)
        self.mvhallLine.setGeometry(QtCore.QRect(110, 150, 161, 27))
        self.mvhallLine.setObjectName("mvhallLine")
        self.mvpriceLine = QtWidgets.QLineEdit(self.newmvFrame)
        self.mvpriceLine.setGeometry(QtCore.QRect(110, 200, 161, 27))
        self.mvpriceLine.setObjectName("mvpriceLine")
        self.yearSpin = QtWidgets.QSpinBox(self.newmvFrame)
        self.yearSpin.setGeometry(QtCore.QRect(110, 240, 101, 31))
        self.yearSpin.setMaximum(2030)
        self.yearSpin.setProperty("value", 2019)
        self.yearSpin.setDisplayIntegerBase(10)
        self.yearSpin.setObjectName("yearSpin")
        self.monSpin = QtWidgets.QSpinBox(self.newmvFrame)
        self.monSpin.setGeometry(QtCore.QRect(110, 280, 101, 27))
        self.monSpin.setMinimum(1)
        self.monSpin.setMaximum(12)
        self.monSpin.setProperty("value", 1)
        self.monSpin.setObjectName("monSpin")
        self.daySpin = QtWidgets.QSpinBox(self.newmvFrame)
        self.daySpin.setGeometry(QtCore.QRect(110, 320, 101, 27))
        self.daySpin.setMinimum(1)
        self.daySpin.setMaximum(31)
        self.daySpin.setObjectName("daySpin")
        self.label_6 = QtWidgets.QLabel(self.newmvFrame)
        self.label_6.setGeometry(QtCore.QRect(220, 240, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.newmvFrame)
        self.label_7.setGeometry(QtCore.QRect(220, 280, 67, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.newmvFrame)
        self.label_8.setGeometry(QtCore.QRect(220, 320, 67, 17))
        self.label_8.setObjectName("label_8")
        self.commit = QtWidgets.QPushButton(self.newmvFrame)
        self.commit.setGeometry(QtCore.QRect(240, 380, 99, 27))
        self.commit.setObjectName("commit")
        self.timeLine = QtWidgets.QLineEdit(self.newmvFrame)
        self.timeLine.setGeometry(QtCore.QRect(110, 360, 113, 27))
        self.timeLine.setObjectName("timeLine")
        self.timelabel = QtWidgets.QLabel(self.newmvFrame)
        self.timelabel.setGeometry(QtCore.QRect(10, 360, 67, 17))
        self.timelabel.setObjectName("timelabel")
        self.hallFrame = QtWidgets.QFrame(Form)
        self.hallFrame.setGeometry(QtCore.QRect(250, 140, 361, 411))
        self.hallFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hallFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hallFrame.setObjectName("hallFrame")
        self.label_2 = QtWidgets.QLabel(self.hallFrame)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.hallFrame)
        self.label_3.setGeometry(QtCore.QRect(90, 50, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.hallFrame)
        self.label_4.setGeometry(QtCore.QRect(160, 50, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.hallFrame)
        self.label_5.setGeometry(QtCore.QRect(240, 50, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.hallFrame)
        self.label_9.setGeometry(QtCore.QRect(30, 90, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.hallFrame)
        self.label_10.setGeometry(QtCore.QRect(90, 90, 67, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.hallFrame)
        self.label_11.setGeometry(QtCore.QRect(180, 90, 67, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.hallFrame)
        self.label_12.setGeometry(QtCore.QRect(260, 90, 67, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.hallFrame)
        self.label_13.setGeometry(QtCore.QRect(260, 130, 67, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.hallFrame)
        self.label_14.setGeometry(QtCore.QRect(90, 130, 67, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.hallFrame)
        self.label_15.setGeometry(QtCore.QRect(180, 130, 67, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.hallFrame)
        self.label_16.setGeometry(QtCore.QRect(30, 130, 67, 17))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.hallFrame)
        self.label_17.setGeometry(QtCore.QRect(260, 170, 67, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.hallFrame)
        self.label_18.setGeometry(QtCore.QRect(90, 170, 67, 17))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.hallFrame)
        self.label_19.setGeometry(QtCore.QRect(180, 170, 67, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.hallFrame)
        self.label_20.setGeometry(QtCore.QRect(30, 170, 67, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.hallFrame)
        self.label_21.setGeometry(QtCore.QRect(260, 200, 67, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.hallFrame)
        self.label_22.setGeometry(QtCore.QRect(90, 240, 67, 17))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.hallFrame)
        self.label_23.setGeometry(QtCore.QRect(90, 200, 67, 17))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.hallFrame)
        self.label_24.setGeometry(QtCore.QRect(180, 200, 67, 17))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.hallFrame)
        self.label_25.setGeometry(QtCore.QRect(180, 240, 67, 17))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.hallFrame)
        self.label_26.setGeometry(QtCore.QRect(180, 280, 67, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.hallFrame)
        self.label_27.setGeometry(QtCore.QRect(30, 200, 67, 17))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.hallFrame)
        self.label_28.setGeometry(QtCore.QRect(90, 280, 67, 17))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.hallFrame)
        self.label_29.setGeometry(QtCore.QRect(260, 280, 67, 17))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.hallFrame)
        self.label_30.setGeometry(QtCore.QRect(30, 240, 67, 17))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.hallFrame)
        self.label_31.setGeometry(QtCore.QRect(260, 240, 67, 17))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.hallFrame)
        self.label_32.setGeometry(QtCore.QRect(30, 280, 67, 17))
        self.label_32.setObjectName("label_32")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 140, 201, 411))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(40, 160, 99, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 220, 99, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 280, 99, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 340, 99, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 50, 131, 61))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.manwel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">欢迎您，管理员</span></p></body></html>"))
        self.newMovie.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">新增电影及排片</span></p></body></html>"))
        self.mvname.setText(_translate("Form", "电影名"))
        self.mvhall.setText(_translate("Form", "厅号"))
        self.mvprice.setText(_translate("Form", "价格"))
        self.mvdate.setText(_translate("Form", "日期"))
        self.label_6.setText(_translate("Form", "年"))
        self.label_7.setText(_translate("Form", "月"))
        self.label_8.setText(_translate("Form", "日"))
        self.commit.setText(_translate("Form", "提交"))
        self.label_2.setText(_translate("Form", "厅号"))
        self.label_3.setText(_translate("Form", "总人数"))
        self.label_4.setText(_translate("Form", "行"))
        self.label_5.setText(_translate("Form", "列"))
        self.label_9.setText(_translate("Form", "1"))
        self.label_10.setText(_translate("Form", "50"))
        self.label_11.setText(_translate("Form", "5"))
        self.label_12.setText(_translate("Form", "10"))
        self.label_13.setText(_translate("Form", "10"))
        self.label_14.setText(_translate("Form", "50"))
        self.label_15.setText(_translate("Form", "5"))
        self.label_16.setText(_translate("Form", "2"))
        self.label_17.setText(_translate("Form", "10"))
        self.label_18.setText(_translate("Form", "70"))
        self.label_19.setText(_translate("Form", "7"))
        self.label_20.setText(_translate("Form", "3"))
        self.label_21.setText(_translate("Form", "10"))
        self.label_22.setText(_translate("Form", "100"))
        self.label_23.setText(_translate("Form", "70"))
        self.label_24.setText(_translate("Form", "7"))
        self.label_25.setText(_translate("Form", "5"))
        self.label_26.setText(_translate("Form", "5"))
        self.label_27.setText(_translate("Form", "4"))
        self.label_28.setText(_translate("Form", "100"))
        self.label_29.setText(_translate("Form", "20"))
        self.label_30.setText(_translate("Form", "5"))
        self.label_31.setText(_translate("Form", "20"))
        self.label_32.setText(_translate("Form", "6"))
        self.pushButton.setText(_translate("Form", "电影管理"))
        self.pushButton_2.setText(_translate("Form", "用户管理"))
        self.pushButton_3.setText(_translate("Form", "厅信息"))
        self.pushButton_4.setText(_translate("Form", "排片信息"))
        self.timelabel.setText(_translate("Form", "时间点"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:20pt;\">功能列表</span></p></body></html>"))


