# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'third2.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(702, 564)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.movieLabel = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("URW Chancery L")
        font.setPointSize(28)
        font.setItalic(True)
        self.movieLabel.setFont(font)
        self.movieLabel.setObjectName("movieLabel")
        self.verticalLayout_3.addWidget(self.movieLabel)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox24 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox24.setText("")
        self.checkBox24.setObjectName("checkBox24")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.checkBox24, 24)
        self.gridLayout_6.addWidget(self.checkBox24, 1, 3, 1, 1)
        self.checkBox43 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox43.setText("")
        self.checkBox43.setObjectName("checkBox43")
        self.buttonGroup.addButton(self.checkBox43, 43)
        self.gridLayout_6.addWidget(self.checkBox43, 2, 2, 1, 1)
        self.checkBox7 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox7.setText("")
        self.checkBox7.setObjectName("checkBox7")
        self.buttonGroup.addButton(self.checkBox7, 7)
        self.gridLayout_6.addWidget(self.checkBox7, 0, 6, 1, 1)
        self.checkBox44 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox44.setText("")
        self.checkBox44.setObjectName("checkBox44")
        self.buttonGroup.addButton(self.checkBox44, 44)
        self.gridLayout_6.addWidget(self.checkBox44, 2, 3, 1, 1)
        self.checkBox45 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox45.setText("")
        self.checkBox45.setObjectName("checkBox45")
        self.buttonGroup.addButton(self.checkBox45, 45)
        self.gridLayout_6.addWidget(self.checkBox45, 2, 4, 1, 1)
        self.checkBox4 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox4.setText("")
        self.checkBox4.setObjectName("checkBox4")
        self.buttonGroup.addButton(self.checkBox4, 4)
        self.gridLayout_6.addWidget(self.checkBox4, 0, 3, 1, 1)
        self.checkBox21 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox21.setText("")
        self.checkBox21.setObjectName("checkBox21")
        self.buttonGroup.addButton(self.checkBox21, 21)
        self.gridLayout_6.addWidget(self.checkBox21, 1, 0, 1, 1)
        self.checkBox46 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox46.setText("")
        self.checkBox46.setObjectName("checkBox46")
        self.buttonGroup.addButton(self.checkBox46, 46)
        self.gridLayout_6.addWidget(self.checkBox46, 2, 5, 1, 1)
        self.checkBox23 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox23.setText("")
        self.checkBox23.setObjectName("checkBox23")
        self.buttonGroup.addButton(self.checkBox23, 23)
        self.gridLayout_6.addWidget(self.checkBox23, 1, 2, 1, 1)
        self.checkBox30 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox30.setText("")
        self.checkBox30.setObjectName("checkBox30")
        self.buttonGroup.addButton(self.checkBox30, 30)
        self.gridLayout_6.addWidget(self.checkBox30, 1, 9, 1, 1)
        self.checkBox10 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox10.setText("")
        self.checkBox10.setObjectName("checkBox10")
        self.buttonGroup.addButton(self.checkBox10, 10)
        self.gridLayout_6.addWidget(self.checkBox10, 0, 9, 1, 1)
        self.checkBox22 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox22.setText("")
        self.checkBox22.setObjectName("checkBox22")
        self.buttonGroup.addButton(self.checkBox22, 22)
        self.gridLayout_6.addWidget(self.checkBox22, 1, 1, 1, 1)
        self.checkBox47 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox47.setText("")
        self.checkBox47.setObjectName("checkBox47")
        self.buttonGroup.addButton(self.checkBox47, 47)
        self.gridLayout_6.addWidget(self.checkBox47, 2, 6, 1, 1)
        self.checkBox42 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox42.setText("")
        self.checkBox42.setObjectName("checkBox42")
        self.buttonGroup.addButton(self.checkBox42, 42)
        self.gridLayout_6.addWidget(self.checkBox42, 2, 1, 1, 1)
        self.checkBox29 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox29.setText("")
        self.checkBox29.setObjectName("checkBox29")
        self.buttonGroup.addButton(self.checkBox29, 29)
        self.gridLayout_6.addWidget(self.checkBox29, 1, 8, 1, 1)
        self.checkBox27 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox27.setText("")
        self.checkBox27.setObjectName("checkBox27")
        self.buttonGroup.addButton(self.checkBox27, 27)
        self.gridLayout_6.addWidget(self.checkBox27, 1, 6, 1, 1)
        self.checkBox25 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox25.setText("")
        self.checkBox25.setObjectName("checkBox25")
        self.buttonGroup.addButton(self.checkBox25, 25)
        self.gridLayout_6.addWidget(self.checkBox25, 1, 4, 1, 1)
        self.checkBox9 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox9.setText("")
        self.checkBox9.setObjectName("checkBox9")
        self.buttonGroup.addButton(self.checkBox9, 9)
        self.gridLayout_6.addWidget(self.checkBox9, 0, 8, 1, 1)
        self.checkBox41 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox41.setText("")
        self.checkBox41.setObjectName("checkBox41")
        self.buttonGroup.addButton(self.checkBox41, 41)
        self.gridLayout_6.addWidget(self.checkBox41, 2, 0, 1, 1)
        self.checkBox6 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox6.setText("")
        self.checkBox6.setObjectName("checkBox6")
        self.buttonGroup.addButton(self.checkBox6, 6)
        self.gridLayout_6.addWidget(self.checkBox6, 0, 5, 1, 1)
        self.checkBox49 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox49.setText("")
        self.checkBox49.setObjectName("checkBox49")
        self.buttonGroup.addButton(self.checkBox49, 49)
        self.gridLayout_6.addWidget(self.checkBox49, 2, 8, 1, 1)
        self.checkBox50 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox50.setText("")
        self.checkBox50.setObjectName("checkBox50")
        self.buttonGroup.addButton(self.checkBox50, 50)
        self.gridLayout_6.addWidget(self.checkBox50, 2, 9, 1, 1)
        self.checkBox8 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox8.setText("")
        self.checkBox8.setObjectName("checkBox8")
        self.buttonGroup.addButton(self.checkBox8, 8)
        self.gridLayout_6.addWidget(self.checkBox8, 0, 7, 1, 1)
        self.checkBox28 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox28.setText("")
        self.checkBox28.setObjectName("checkBox28")
        self.buttonGroup.addButton(self.checkBox28, 28)
        self.gridLayout_6.addWidget(self.checkBox28, 1, 7, 1, 1)
        self.checkBox26 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox26.setText("")
        self.checkBox26.setObjectName("checkBox26")
        self.buttonGroup.addButton(self.checkBox26, 26)
        self.gridLayout_6.addWidget(self.checkBox26, 1, 5, 1, 1)
        self.checkBox5 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox5.setText("")
        self.checkBox5.setObjectName("checkBox5")
        self.buttonGroup.addButton(self.checkBox5, 5)
        self.gridLayout_6.addWidget(self.checkBox5, 0, 4, 1, 1)
        self.checkBox3 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox3.setText("")
        self.checkBox3.setObjectName("checkBox3")
        self.buttonGroup.addButton(self.checkBox3, 3)
        self.gridLayout_6.addWidget(self.checkBox3, 0, 2, 1, 1)
        self.checkBox2 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox2.setText("")
        self.checkBox2.setObjectName("checkBox2")
        self.buttonGroup.addButton(self.checkBox2, 2)
        self.gridLayout_6.addWidget(self.checkBox2, 0, 1, 1, 1)
        self.checkBox1 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox1.setText("")
        self.checkBox1.setObjectName("checkBox1")
        self.buttonGroup.addButton(self.checkBox1, 1)
        self.gridLayout_6.addWidget(self.checkBox1, 0, 0, 1, 1)
        self.checkBox48 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox48.setText("")
        self.checkBox48.setObjectName("checkBox48")
        self.buttonGroup.addButton(self.checkBox48, 48)
        self.gridLayout_6.addWidget(self.checkBox48, 2, 7, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox33 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox33.setText("")
        self.checkBox33.setObjectName("checkBox33")
        self.buttonGroup.addButton(self.checkBox33, 33)
        self.gridLayout_8.addWidget(self.checkBox33, 1, 2, 1, 1)
        self.checkBox40 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox40.setText("")
        self.checkBox40.setObjectName("checkBox40")
        self.buttonGroup.addButton(self.checkBox40, 40)
        self.gridLayout_8.addWidget(self.checkBox40, 1, 9, 1, 1)
        self.checkBox16 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox16.setText("")
        self.checkBox16.setObjectName("checkBox16")
        self.buttonGroup.addButton(self.checkBox16, 16)
        self.gridLayout_8.addWidget(self.checkBox16, 0, 5, 1, 1)
        self.checkBox11 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox11.setText("")
        self.checkBox11.setObjectName("checkBox11")
        self.buttonGroup.addButton(self.checkBox11, 11)
        self.gridLayout_8.addWidget(self.checkBox11, 0, 0, 1, 1)
        self.checkBox57 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox57.setText("")
        self.checkBox57.setObjectName("checkBox57")
        self.buttonGroup.addButton(self.checkBox57, 57)
        self.gridLayout_8.addWidget(self.checkBox57, 2, 6, 1, 1)
        self.checkBox39 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox39.setText("")
        self.checkBox39.setObjectName("checkBox39")
        self.buttonGroup.addButton(self.checkBox39, 39)
        self.gridLayout_8.addWidget(self.checkBox39, 1, 8, 1, 1)
        self.checkBox12 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox12.setText("")
        self.checkBox12.setObjectName("checkBox12")
        self.buttonGroup.addButton(self.checkBox12, 12)
        self.gridLayout_8.addWidget(self.checkBox12, 0, 1, 1, 1)
        self.checkBox15 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox15.setText("")
        self.checkBox15.setObjectName("checkBox15")
        self.buttonGroup.addButton(self.checkBox15, 15)
        self.gridLayout_8.addWidget(self.checkBox15, 0, 4, 1, 1)
        self.checkBox36 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox36.setText("")
        self.checkBox36.setObjectName("checkBox36")
        self.buttonGroup.addButton(self.checkBox36, 36)
        self.gridLayout_8.addWidget(self.checkBox36, 1, 5, 1, 1)
        self.checkBox34 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox34.setText("")
        self.checkBox34.setObjectName("checkBox34")
        self.buttonGroup.addButton(self.checkBox34, 34)
        self.gridLayout_8.addWidget(self.checkBox34, 1, 3, 1, 1)
        self.checkBox53 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox53.setText("")
        self.checkBox53.setObjectName("checkBox53")
        self.buttonGroup.addButton(self.checkBox53, 53)
        self.gridLayout_8.addWidget(self.checkBox53, 2, 2, 1, 1)
        self.checkBox54 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox54.setText("")
        self.checkBox54.setObjectName("checkBox54")
        self.buttonGroup.addButton(self.checkBox54, 54)
        self.gridLayout_8.addWidget(self.checkBox54, 2, 3, 1, 1)
        self.checkBox52 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox52.setText("")
        self.checkBox52.setObjectName("checkBox52")
        self.buttonGroup.addButton(self.checkBox52, 52)
        self.gridLayout_8.addWidget(self.checkBox52, 2, 1, 1, 1)
        self.checkBox32 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox32.setText("")
        self.checkBox32.setObjectName("checkBox32")
        self.buttonGroup.addButton(self.checkBox32, 32)
        self.gridLayout_8.addWidget(self.checkBox32, 1, 1, 1, 1)
        self.checkBox60 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox60.setText("")
        self.checkBox60.setObjectName("checkBox60")
        self.buttonGroup.addButton(self.checkBox60, 60)
        self.gridLayout_8.addWidget(self.checkBox60, 2, 9, 1, 1)
        self.checkBox17 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox17.setText("")
        self.checkBox17.setObjectName("checkBox17")
        self.buttonGroup.addButton(self.checkBox17, 17)
        self.gridLayout_8.addWidget(self.checkBox17, 0, 6, 1, 1)
        self.checkBox55 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox55.setText("")
        self.checkBox55.setObjectName("checkBox55")
        self.buttonGroup.addButton(self.checkBox55, 55)
        self.gridLayout_8.addWidget(self.checkBox55, 2, 4, 1, 1)
        self.checkBox14 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox14.setText("")
        self.checkBox14.setObjectName("checkBox14")
        self.buttonGroup.addButton(self.checkBox14, 14)
        self.gridLayout_8.addWidget(self.checkBox14, 0, 3, 1, 1)
        self.checkBox35 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox35.setText("")
        self.checkBox35.setObjectName("checkBox35")
        self.buttonGroup.addButton(self.checkBox35, 35)
        self.gridLayout_8.addWidget(self.checkBox35, 1, 4, 1, 1)
        self.checkBox31 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox31.setText("")
        self.checkBox31.setObjectName("checkBox31")
        self.buttonGroup.addButton(self.checkBox31, 31)
        self.gridLayout_8.addWidget(self.checkBox31, 1, 0, 1, 1)
        self.checkBox20 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox20.setText("")
        self.checkBox20.setObjectName("checkBox20")
        self.buttonGroup.addButton(self.checkBox20, 20)
        self.gridLayout_8.addWidget(self.checkBox20, 0, 9, 1, 1)
        self.checkBox38 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox38.setText("")
        self.checkBox38.setObjectName("checkBox38")
        self.buttonGroup.addButton(self.checkBox38, 38)
        self.gridLayout_8.addWidget(self.checkBox38, 1, 7, 1, 1)
        self.checkBox18 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox18.setText("")
        self.checkBox18.setObjectName("checkBox18")
        self.buttonGroup.addButton(self.checkBox18, 18)
        self.gridLayout_8.addWidget(self.checkBox18, 0, 7, 1, 1)
        self.checkBox59 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox59.setText("")
        self.checkBox59.setObjectName("checkBox59")
        self.buttonGroup.addButton(self.checkBox59, 59)
        self.gridLayout_8.addWidget(self.checkBox59, 2, 8, 1, 1)
        self.checkBox13 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox13.setText("")
        self.checkBox13.setObjectName("checkBox13")
        self.buttonGroup.addButton(self.checkBox13, 13)
        self.gridLayout_8.addWidget(self.checkBox13, 0, 2, 1, 1)
        self.checkBox51 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox51.setText("")
        self.checkBox51.setObjectName("checkBox51")
        self.buttonGroup.addButton(self.checkBox51, 51)
        self.gridLayout_8.addWidget(self.checkBox51, 2, 0, 1, 1)
        self.checkBox19 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox19.setText("")
        self.checkBox19.setObjectName("checkBox19")
        self.buttonGroup.addButton(self.checkBox19, 19)
        self.gridLayout_8.addWidget(self.checkBox19, 0, 8, 1, 1)
        self.checkBox37 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox37.setText("")
        self.checkBox37.setObjectName("checkBox37")
        self.buttonGroup.addButton(self.checkBox37, 37)
        self.gridLayout_8.addWidget(self.checkBox37, 1, 6, 1, 1)
        self.checkBox58 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox58.setText("")
        self.checkBox58.setObjectName("checkBox58")
        self.buttonGroup.addButton(self.checkBox58, 58)
        self.gridLayout_8.addWidget(self.checkBox58, 2, 7, 1, 1)
        self.checkBox56 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox56.setText("")
        self.checkBox56.setObjectName("checkBox56")
        self.buttonGroup.addButton(self.checkBox56, 56)
        self.gridLayout_8.addWidget(self.checkBox56, 2, 5, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.checkBox84 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox84.setText("")
        self.checkBox84.setObjectName("checkBox84")
        self.buttonGroup.addButton(self.checkBox84, 84)
        self.gridLayout_9.addWidget(self.checkBox84, 1, 3, 1, 1)
        self.checkBox104 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox104.setText("")
        self.checkBox104.setObjectName("checkBox104")
        self.buttonGroup.addButton(self.checkBox104, 104)
        self.gridLayout_9.addWidget(self.checkBox104, 2, 3, 1, 1)
        self.checkBox105 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox105.setText("")
        self.checkBox105.setObjectName("checkBox105")
        self.buttonGroup.addButton(self.checkBox105, 105)
        self.gridLayout_9.addWidget(self.checkBox105, 2, 4, 1, 1)
        self.checkBox87 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox87.setEnabled(True)
        self.checkBox87.setText("")
        self.checkBox87.setObjectName("checkBox87")
        self.buttonGroup.addButton(self.checkBox87, 87)
        self.gridLayout_9.addWidget(self.checkBox87, 1, 6, 1, 1)
        self.checkBox85 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox85.setText("")
        self.checkBox85.setObjectName("checkBox85")
        self.buttonGroup.addButton(self.checkBox85, 85)
        self.gridLayout_9.addWidget(self.checkBox85, 1, 4, 1, 1)
        self.checkBox89 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox89.setText("")
        self.checkBox89.setObjectName("checkBox89")
        self.buttonGroup.addButton(self.checkBox89, 89)
        self.gridLayout_9.addWidget(self.checkBox89, 1, 8, 1, 1)
        self.checkBox66 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox66.setText("")
        self.checkBox66.setObjectName("checkBox66")
        self.buttonGroup.addButton(self.checkBox66, 66)
        self.gridLayout_9.addWidget(self.checkBox66, 0, 5, 1, 1)
        self.checkBox69 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox69.setText("")
        self.checkBox69.setObjectName("checkBox69")
        self.buttonGroup.addButton(self.checkBox69, 69)
        self.gridLayout_9.addWidget(self.checkBox69, 0, 8, 1, 1)
        self.checkBox101 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox101.setText("")
        self.checkBox101.setObjectName("checkBox101")
        self.buttonGroup.addButton(self.checkBox101, 101)
        self.gridLayout_9.addWidget(self.checkBox101, 2, 0, 1, 1)
        self.checkBox83 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox83.setText("")
        self.checkBox83.setObjectName("checkBox83")
        self.buttonGroup.addButton(self.checkBox83, 83)
        self.gridLayout_9.addWidget(self.checkBox83, 1, 2, 1, 1)
        self.checkBox90 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox90.setText("")
        self.checkBox90.setObjectName("checkBox90")
        self.buttonGroup.addButton(self.checkBox90, 90)
        self.gridLayout_9.addWidget(self.checkBox90, 1, 9, 1, 1)
        self.checkBox70 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox70.setText("")
        self.checkBox70.setObjectName("checkBox70")
        self.buttonGroup.addButton(self.checkBox70, 70)
        self.gridLayout_9.addWidget(self.checkBox70, 0, 9, 1, 1)
        self.checkBox82 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox82.setText("")
        self.checkBox82.setObjectName("checkBox82")
        self.buttonGroup.addButton(self.checkBox82, 82)
        self.gridLayout_9.addWidget(self.checkBox82, 1, 1, 1, 1)
        self.checkBox81 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox81.setText("")
        self.checkBox81.setObjectName("checkBox81")
        self.buttonGroup.addButton(self.checkBox81, 81)
        self.gridLayout_9.addWidget(self.checkBox81, 1, 0, 1, 1)
        self.checkBox106 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox106.setText("")
        self.checkBox106.setObjectName("checkBox106")
        self.buttonGroup.addButton(self.checkBox106, 106)
        self.gridLayout_9.addWidget(self.checkBox106, 2, 5, 1, 1)
        self.checkBox109 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox109.setText("")
        self.checkBox109.setObjectName("checkBox109")
        self.buttonGroup.addButton(self.checkBox109, 109)
        self.gridLayout_9.addWidget(self.checkBox109, 2, 8, 1, 1)
        self.checkBox88 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox88.setText("")
        self.checkBox88.setObjectName("checkBox88")
        self.buttonGroup.addButton(self.checkBox88, 88)
        self.gridLayout_9.addWidget(self.checkBox88, 1, 7, 1, 1)
        self.checkBox110 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox110.setText("")
        self.checkBox110.setObjectName("checkBox110")
        self.buttonGroup.addButton(self.checkBox110, 110)
        self.gridLayout_9.addWidget(self.checkBox110, 2, 9, 1, 1)
        self.checkBox68 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox68.setText("")
        self.checkBox68.setObjectName("checkBox68")
        self.buttonGroup.addButton(self.checkBox68, 68)
        self.gridLayout_9.addWidget(self.checkBox68, 0, 7, 1, 1)
        self.checkBox63 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox63.setText("")
        self.checkBox63.setObjectName("checkBox63")
        self.buttonGroup.addButton(self.checkBox63, 63)
        self.gridLayout_9.addWidget(self.checkBox63, 0, 2, 1, 1)
        self.checkBox86 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox86.setText("")
        self.checkBox86.setObjectName("checkBox86")
        self.buttonGroup.addButton(self.checkBox86, 86)
        self.gridLayout_9.addWidget(self.checkBox86, 1, 5, 1, 1)
        self.checkBox62 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox62.setText("")
        self.checkBox62.setObjectName("checkBox62")
        self.buttonGroup.addButton(self.checkBox62, 62)
        self.gridLayout_9.addWidget(self.checkBox62, 0, 1, 1, 1)
        self.checkBox65 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox65.setText("")
        self.checkBox65.setObjectName("checkBox65")
        self.buttonGroup.addButton(self.checkBox65, 65)
        self.gridLayout_9.addWidget(self.checkBox65, 0, 4, 1, 1)
        self.checkBox61 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox61.setText("")
        self.checkBox61.setObjectName("checkBox61")
        self.buttonGroup.addButton(self.checkBox61, 61)
        self.gridLayout_9.addWidget(self.checkBox61, 0, 0, 1, 1)
        self.checkBox108 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox108.setText("")
        self.checkBox108.setObjectName("checkBox108")
        self.buttonGroup.addButton(self.checkBox108, 108)
        self.gridLayout_9.addWidget(self.checkBox108, 2, 7, 1, 1)
        self.checkBox107 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox107.setText("")
        self.checkBox107.setObjectName("checkBox107")
        self.buttonGroup.addButton(self.checkBox107, 107)
        self.gridLayout_9.addWidget(self.checkBox107, 2, 6, 1, 1)
        self.checkBox102 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox102.setText("")
        self.checkBox102.setObjectName("checkBox102")
        self.buttonGroup.addButton(self.checkBox102, 102)
        self.gridLayout_9.addWidget(self.checkBox102, 2, 1, 1, 1)
        self.checkBox64 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox64.setText("")
        self.checkBox64.setObjectName("checkBox64")
        self.buttonGroup.addButton(self.checkBox64, 64)
        self.gridLayout_9.addWidget(self.checkBox64, 0, 3, 1, 1)
        self.checkBox67 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox67.setText("")
        self.checkBox67.setObjectName("checkBox67")
        self.buttonGroup.addButton(self.checkBox67, 67)
        self.gridLayout_9.addWidget(self.checkBox67, 0, 6, 1, 1)
        self.checkBox103 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox103.setText("")
        self.checkBox103.setObjectName("checkBox103")
        self.buttonGroup.addButton(self.checkBox103, 103)
        self.gridLayout_9.addWidget(self.checkBox103, 2, 2, 1, 1)
        self.horizontalLayout.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.checkBox94 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox94.setText("")
        self.checkBox94.setObjectName("checkBox94")
        self.buttonGroup.addButton(self.checkBox94, 94)
        self.gridLayout_10.addWidget(self.checkBox94, 1, 3, 1, 1)
        self.checkBox113 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox113.setText("")
        self.checkBox113.setObjectName("checkBox113")
        self.buttonGroup.addButton(self.checkBox113, 113)
        self.gridLayout_10.addWidget(self.checkBox113, 2, 2, 1, 1)
        self.checkBox77 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox77.setText("")
        self.checkBox77.setObjectName("checkBox77")
        self.buttonGroup.addButton(self.checkBox77, 77)
        self.gridLayout_10.addWidget(self.checkBox77, 0, 6, 1, 1)
        self.checkBox114 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox114.setText("")
        self.checkBox114.setObjectName("checkBox114")
        self.buttonGroup.addButton(self.checkBox114, 114)
        self.gridLayout_10.addWidget(self.checkBox114, 2, 3, 1, 1)
        self.checkBox115 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox115.setText("")
        self.checkBox115.setObjectName("checkBox115")
        self.buttonGroup.addButton(self.checkBox115, 115)
        self.gridLayout_10.addWidget(self.checkBox115, 2, 4, 1, 1)
        self.checkBox74 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox74.setText("")
        self.checkBox74.setObjectName("checkBox74")
        self.buttonGroup.addButton(self.checkBox74, 74)
        self.gridLayout_10.addWidget(self.checkBox74, 0, 3, 1, 1)
        self.checkBox91 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox91.setText("")
        self.checkBox91.setObjectName("checkBox91")
        self.buttonGroup.addButton(self.checkBox91, 91)
        self.gridLayout_10.addWidget(self.checkBox91, 1, 0, 1, 1)
        self.checkBox116 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox116.setText("")
        self.checkBox116.setObjectName("checkBox116")
        self.buttonGroup.addButton(self.checkBox116, 116)
        self.gridLayout_10.addWidget(self.checkBox116, 2, 5, 1, 1)
        self.checkBox93 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox93.setText("")
        self.checkBox93.setObjectName("checkBox93")
        self.buttonGroup.addButton(self.checkBox93, 93)
        self.gridLayout_10.addWidget(self.checkBox93, 1, 2, 1, 1)
        self.checkBox100 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox100.setText("")
        self.checkBox100.setObjectName("checkBox100")
        self.buttonGroup.addButton(self.checkBox100, 100)
        self.gridLayout_10.addWidget(self.checkBox100, 1, 9, 1, 1)
        self.checkBox80 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox80.setText("")
        self.checkBox80.setObjectName("checkBox80")
        self.buttonGroup.addButton(self.checkBox80, 80)
        self.gridLayout_10.addWidget(self.checkBox80, 0, 9, 1, 1)
        self.checkBox92 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox92.setText("")
        self.checkBox92.setObjectName("checkBox92")
        self.buttonGroup.addButton(self.checkBox92, 92)
        self.gridLayout_10.addWidget(self.checkBox92, 1, 1, 1, 1)
        self.checkBox117 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox117.setText("")
        self.checkBox117.setObjectName("checkBox117")
        self.buttonGroup.addButton(self.checkBox117, 117)
        self.gridLayout_10.addWidget(self.checkBox117, 2, 6, 1, 1)
        self.checkBox112 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox112.setText("")
        self.checkBox112.setObjectName("checkBox112")
        self.buttonGroup.addButton(self.checkBox112, 112)
        self.gridLayout_10.addWidget(self.checkBox112, 2, 1, 1, 1)
        self.checkBox99 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox99.setText("")
        self.checkBox99.setObjectName("checkBox99")
        self.buttonGroup.addButton(self.checkBox99, 99)
        self.gridLayout_10.addWidget(self.checkBox99, 1, 8, 1, 1)
        self.checkBox97 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox97.setText("")
        self.checkBox97.setObjectName("checkBox97")
        self.buttonGroup.addButton(self.checkBox97, 97)
        self.gridLayout_10.addWidget(self.checkBox97, 1, 6, 1, 1)
        self.checkBox95 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox95.setText("")
        self.checkBox95.setObjectName("checkBox95")
        self.buttonGroup.addButton(self.checkBox95, 95)
        self.gridLayout_10.addWidget(self.checkBox95, 1, 4, 1, 1)
        self.checkBox79 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox79.setText("")
        self.checkBox79.setObjectName("checkBox79")
        self.buttonGroup.addButton(self.checkBox79, 79)
        self.gridLayout_10.addWidget(self.checkBox79, 0, 8, 1, 1)
        self.checkBox111 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox111.setText("")
        self.checkBox111.setObjectName("checkBox111")
        self.buttonGroup.addButton(self.checkBox111, 111)
        self.gridLayout_10.addWidget(self.checkBox111, 2, 0, 1, 1)
        self.checkBox76 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox76.setText("")
        self.checkBox76.setObjectName("checkBox76")
        self.buttonGroup.addButton(self.checkBox76, 76)
        self.gridLayout_10.addWidget(self.checkBox76, 0, 5, 1, 1)
        self.checkBox119 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox119.setText("")
        self.checkBox119.setObjectName("checkBox119")
        self.buttonGroup.addButton(self.checkBox119, 119)
        self.gridLayout_10.addWidget(self.checkBox119, 2, 8, 1, 1)
        self.checkBox120 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox120.setText("")
        self.checkBox120.setObjectName("checkBox120")
        self.buttonGroup.addButton(self.checkBox120, 120)
        self.gridLayout_10.addWidget(self.checkBox120, 2, 9, 1, 1)
        self.checkBox78 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox78.setText("")
        self.checkBox78.setObjectName("checkBox78")
        self.buttonGroup.addButton(self.checkBox78, 78)
        self.gridLayout_10.addWidget(self.checkBox78, 0, 7, 1, 1)
        self.checkBox98 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox98.setText("")
        self.checkBox98.setObjectName("checkBox98")
        self.buttonGroup.addButton(self.checkBox98, 98)
        self.gridLayout_10.addWidget(self.checkBox98, 1, 7, 1, 1)
        self.checkBox96 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox96.setText("")
        self.checkBox96.setObjectName("checkBox96")
        self.buttonGroup.addButton(self.checkBox96, 96)
        self.gridLayout_10.addWidget(self.checkBox96, 1, 5, 1, 1)
        self.checkBox75 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox75.setText("")
        self.checkBox75.setObjectName("checkBox75")
        self.buttonGroup.addButton(self.checkBox75, 75)
        self.gridLayout_10.addWidget(self.checkBox75, 0, 4, 1, 1)
        self.checkBox73 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox73.setText("")
        self.checkBox73.setObjectName("checkBox73")
        self.buttonGroup.addButton(self.checkBox73, 73)
        self.gridLayout_10.addWidget(self.checkBox73, 0, 2, 1, 1)
        self.checkBox72 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox72.setText("")
        self.checkBox72.setObjectName("checkBox72")
        self.buttonGroup.addButton(self.checkBox72, 72)
        self.gridLayout_10.addWidget(self.checkBox72, 0, 1, 1, 1)
        self.checkBox71 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox71.setText("")
        self.checkBox71.setObjectName("checkBox71")
        self.buttonGroup.addButton(self.checkBox71, 71)
        self.gridLayout_10.addWidget(self.checkBox71, 0, 0, 1, 1)
        self.checkBox118 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox118.setText("")
        self.checkBox118.setObjectName("checkBox118")
        self.buttonGroup.addButton(self.checkBox118, 118)
        self.gridLayout_10.addWidget(self.checkBox118, 2, 7, 1, 1)
        self.horizontalLayout.addWidget(self.frame_9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.frame5 = QtWidgets.QFrame(self.frame)
        self.frame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame5.setObjectName("frame5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shopFrame = QtWidgets.QFrame(self.frame5)
        self.shopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shopFrame.setObjectName("shopFrame")
        self.commitButton = QtWidgets.QPushButton(self.shopFrame)
        self.commitButton.setGeometry(QtCore.QRect(20, 120, 91, 27))
        font = QtGui.QFont()
        font.setFamily("URW Chancery L")
        font.setPointSize(16)
        font.setItalic(True)
        self.commitButton.setFont(font)
        self.commitButton.setObjectName("commitButton")
        self.totalLabel = QtWidgets.QLabel(self.shopFrame)
        self.totalLabel.setGeometry(QtCore.QRect(10, 90, 121, 21))
        font = QtGui.QFont()
        font.setFamily("URW Chancery L")
        font.setPointSize(14)
        font.setItalic(True)
        self.totalLabel.setFont(font)
        self.totalLabel.setObjectName("totalLabel")
        self.titleLabel = QtWidgets.QLabel(self.shopFrame)
        self.titleLabel.setGeometry(QtCore.QRect(10, 10, 121, 71))
        font = QtGui.QFont()
        font.setFamily("URW Chancery L")
        font.setPointSize(16)
        font.setItalic(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.shopFrame)
        self.horizontalLayout_3.addWidget(self.frame5)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.movieLabel.setText(_translate("Form", "                 Movie Stage"))
        self.commitButton.setText(_translate("Form", "Buy It!"))
        self.totalLabel.setText(_translate("Form", "Total:"))
        self.titleLabel.setText(_translate("Form", "    Enjob  It !"))


